export enum QuoteType {
    EQUITY = 'EQUITY',
    FUTURE = 'FUTURE',
    INDEX = 'INDEX',
    OPTION = 'OPTION',
    MUTUALFUND = 'MUTUALFUND',
    CRYPTOCURRENCY = 'CRYPTOCURRENCY',
    CURRENCY = 'CURRENCY',
    ETF = 'ETF',
}
